In [1]:
from lab1.part1.algorithms.delta import delta_rule, delta_predict
from lab1.part1.algorithms.perceptron import perceptron_learning
import numpy as np

## Q3 2020/10/20

In [2]:
w_init = np.array([[1,0,-1,0], [0,-3,-1,1]], dtype='float64') 
X =  np.array([[1,1,-1], [-1,-1,2], [1,0,1]])
y =  np.array([[-1,-1],[1,1],[1,-1]]).T
w_per, history = delta_rule(X, y, lr=0.1, max_iters=2,w_init=w_init)
w_per

array([[ 0.34, -0.78,  0.31,  0.16],
       [-0.06, -2.91, -1.35,  0.72]])

In [3]:
y_pred = delta_predict(X, w_per.T) 
y_pred

(4, 2)
(3, 4)


array([[-1., -1.],
       [ 1.,  1.],
       [ 1., -1.]])

## Same with perceptron Q3 2020/12/16

In [35]:
lr = 0.5
w = np.array([[1,1,1], [1,1,1]], dtype='float64')
# print(w)
X =  np.array([[2,1], [1,1], [-2,0], [0,1], [1,-1]])
X = np.c_[X, np.ones(X.shape[0])]
X = X.T
# print(X)
y =  np.array([[0,0],[0,0],[1,0],[1,0],[0,1]]).T
# print(y)
epochs = 1
for _ in range(epochs):
    update = w @ X
    # print(update) 
    update = np.heaviside(update, 0)
    # print(update)
    e = y - update
    # print(e)
    w += lr * e @ X.T
print(w)
y_pred = np.heaviside(w @ X, 0)
y_pred

[[-2.   0.5  0. ]
 [-0.5 -0.5 -0.5]]


array([[0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0.]])

## Hopfield