In [1]:
import importlib
import numpy as np
import hopfieldNetwork as hn
import matplotlib.pyplot as plt

## 3.1 Convergence and Attractors

In [20]:
N = 8
log2N = int(np.log2(N))
x1 = np.array([-1, -1, 1, -1, 1, -1, -1, 1])
x2 = np.array([-1, -1, -1, -1, -1, 1, -1, -1])
x3 = np.array([-1, 1, 1, -1, -1, 1, -1, 1])

patterns= np.array([x1, x2, x3])

In [21]:
importlib.reload(hn)
hop_net1 = hn.HopfieldNetwork(patterns)
hop_net1.check_storage()

Fixed Point found after 3 iterations!
Convergence towards stored pattern nb 0!
[-1 -1  1 -1  1 -1 -1  1] 

Fixed Point found after 3 iterations!
Convergence towards stored pattern nb 1!
[-1 -1 -1 -1 -1  1 -1 -1] 

Fixed Point found after 3 iterations!
Convergence towards stored pattern nb 2!
[-1  1  1 -1 -1  1 -1  1] 



In [22]:
x1d = np.array([1, -1, 1, -1, 1, -1, -1, 1])
x2d = np.array([1, 1, -1, -1, -1, 1, -1, -1])
x3d = np.array([1, 1, 1, -1, 1, 1, -1, 1])

destroyed_patterns = np.array([x1d, x2d, x3d])

In [23]:
importlib.reload(hn)
hop_net1 = hn.HopfieldNetwork(patterns)
for p in destroyed_patterns:
    inter_patterns, _, _ = hop_net1.update_rule(p, max_iter=log2N)
    # for i, ip in enumerate(reversed(inter_patterns)):
    #     print(i, ip)

Fixed Point found after 3 iterations!
Convergence towards stored pattern nb 0!
[-1 -1  1 -1  1 -1 -1  1] 

Fixed Point found after 3 iterations!
This pattern is an attractor!
[-1.  1. -1. -1. -1.  1. -1. -1.] 

Fixed Point found after 3 iterations!
Convergence towards stored pattern nb 2!
[-1  1  1 -1 -1  1 -1  1] 



In [24]:
importlib.reload(hn)
hop_net1 = hn.HopfieldNetwork(patterns)
attractors = hop_net1.find_attractors()
attractors.shape

[-1  1 -1 -1 -1  1 -1 -1] eeoeoeo [-1.  1. -1. -1. -1.  1. -1. -1.]


(14, 8)

In [25]:
x3dd = np.array([1, -1, -1, 1, 1, 1, -1, 1])
inter_patterns, _, _ = hop_net1.update_rule(x3dd, max_iter=log2N)

Fixed Point found after 3 iterations!
This pattern is an attractor!
[ 1. -1. -1.  1.  1. -1.  1. -1.] 

