In [4]:
import importlib
import numpy as np
import hopfieldNetwork as hn

## 3.1 Convergence and Attractors

In [74]:
N = 8
log2N = int(np.log2(N))
x1 = np.array([-1, -1, 1, -1, 1, -1, -1, 1])
x2 = np.array([-1, -1, -1, -1, -1, 1, -1, -1])
x3 = np.array([-1, 1, 1, -1, -1, 1, -1, 1])

patterns= np.array([x1, x2, x3])

In [88]:
importlib.reload(hn)
hop_net1 = hn.HopfieldNetwork(patterns)
hop_net1.check_storage()

Fixed Point found after 2 iterations!
Convergence towards stored pattern nb 0!
[-1 -1  1 -1  1 -1 -1  1] 

Fixed Point found after 2 iterations!
Convergence towards stored pattern nb 1!
[-1 -1 -1 -1 -1  1 -1 -1] 

Fixed Point found after 2 iterations!
Convergence towards stored pattern nb 2!
[-1  1  1 -1 -1  1 -1  1] 



In [64]:
x1d = np.array([1, -1, 1, -1, 1, -1, -1, 1])
x2d = np.array([1, 1, -1, -1, -1, 1, -1, -1])
x3d = np.array([1, 1, 1, -1, 1, 1, -1, 1])

destroyed_patterns = np.array([x1d, x2d, x3d])

In [89]:
importlib.reload(hn)
hop_net1 = hn.HopfieldNetwork(patterns)
for p in destroyed_patterns:
    inter_patterns, _ = hop_net1.update_rule(p, max_iter=log2N)
    # for i, ip in enumerate(reversed(inter_patterns)):
    #     print(i, ip)

Fixed Point found after 2 iterations!
Convergence towards stored pattern nb 0!
[-1 -1  1 -1  1 -1 -1  1] 

Fixed Point found after 2 iterations!
Convergence towards stored pattern nb 1!
[-1 -1 -1 -1 -1  1 -1 -1] 

Fixed Point found after 2 iterations!
Convergence towards stored pattern nb 2!
[-1  1  1 -1 -1  1 -1  1] 



In [93]:
importlib.reload(hn)
hop_net1 = hn.HopfieldNetwork(patterns)
attractors = hop_net1.find_attractors()
attractors.shape

(163, 8)